### PR TITLE
changed Admin EditText fields to hint their respective strings

### PR DESCRIPTION
**Pull request by oneSIX**

### CODE REVIEW

**Comment by oneSIX** [comment]
@seitensei I don't quite follow what you mean.

**Comment by oneSIX** [comment]
Changes completed.

**Comment by seitensei** [comment]
Talked to @oneSIX and he tested null changes on device. Go ahead and merge.

**Comment by seitensei** [comment]
@peterse2 I'm not sure what you mean. No actual UI changes were made except for showing hint text.

**Pull request merged**
